### ISSUE TITLE
3DR no longer making APM 2.6 boards?

### ISSUE THREAD

**Issue by nonstop99** [bluerobotics/SolarSurferCore#1]
Apparently 3DR no longer make the APM 2.6

so can we use APM 2.8 instead?

like this one..

https://www.unmannedtechshop.co.uk/ardupilot-mega-autopilot-kit-apm-2-8/

**Comment by jaxxzer** [comment]
The apm boards will have to be sourced from a different supplier. APM 2.6 and APM 2.8 are usually compatible.
